version: '3.8'
services:
  postgress:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=africa
      - POSTGRES_PASSWORD=village_people
    volumes:
      - /path/on/host/machine:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes: 
  postgres:
